"""Small declarative animation library. Durations are seconds, poses are held."""

# Twenty new local actions. Each sequence is distinct and usable by the controller.
ACTIONS = {
    "scoot": (1.4, ("idle", "scoot_front", "drag_tail", "idle"), "move"),
    "crawl": (2.2, ("scoot_front", "crawl_bridge", "drag_tail", "idle"), "move"),
    "roll": (1.8, ("squash", "rolling_ball", "twisted", "side_flop", "idle"), "move"),
    "tiptoe": (2.4, ("curious_lean", "tiptoe", "bob", "tiptoe", "idle"), "move"),
    "pace": (3.6, ("scoot_front", "drag_tail", "twisted", "scoot_front", "idle"), "pace"),
    "edge_peek": (2.2, ("idle", "scoot_front", "curious_lean", "curious_lean", "idle"), "edge"),
    "retreat": (1.6, ("lean_back", "drag_tail", "scoot_front", "idle"), "move"),
    "turn": (1.2, ("idle", "curious_lean", "twisted", "idle"), "turn"),
    "bounce": (1.3, ("squash", "vertical_noodle", "air", "impact", "idle"), "bounce"),
    "dance": (2.4, ("proud", "squash", "twisted", "rebound", "jiggle", "idle"), "dance"),
    "spin": (1.6, ("spiral", "twisted", "rolling_ball", "crown_ripple", "idle"), "turn"),
    "somersault": (1.8, ("squash", "rolling_ball", "side_flop", "asym_impact", "idle"), "tumble"),
    "yawn": (2.5, ("slump", "vertical_noodle", "double_arch", "breathe", "idle"), "still"),
    "melt": (3.0, ("breathe", "slump", "jiggle", "puddle", "puddle"), "still"),
    "reform": (2.4, ("puddle", "jiggle", "rebound", "proud", "idle"), "still"),
    "scratch": (2.0, ("curious_lean", "twisted", "curious_lean", "idle"), "scratch"),
    "applaud": (2.0, ("proud", "double_arch", "breathe", "double_arch", "idle"), "clap"),
    "cheer": (2.0, ("squash", "double_arch", "proud", "rebound", "idle"), "cheer"),
    "nod": (1.4, ("proud", "slump", "proud", "slump", "idle"), "still"),
    "shake_head": (1.5, ("idle", "twisted", "lean_back", "twisted", "crown_ripple"), "shake"),
}

# prepare, flight, landing, arc multiplier, airborne poses. No 60Hz art generation.
HOPS = {
    "classic": (0.6, 0.7, 0.5, 1.0, ("launch", "launch", "air", "apex", "apex", "fall", "fall")),
    "fluid": (0.6, 0.7, 0.5, 1.0, ("launch", "stretch", "air", "apex", "apex", "air", "fall", "stretch", "fall")),
    "tiny": (0.3, 0.45, 0.35, 0.35, ("stretch", "air", "fall")),
    "bunny": (0.65, 0.65, 0.6, 0.7, ("launch", "air", "apex", "fall")),
    "heavy": (0.8, 0.6, 0.75, 0.9, ("vertical_noodle", "air", "fall", "asym_impact")),
    "floaty": (0.6, 1.25, 0.6, 1.4, ("stretch", "air", "apex", "apex", "fall")),
    "nervous": (1.0, 0.55, 0.6, 0.65, ("lean_back", "launch", "air", "fall")),
    "excited": (0.65, 0.65, 0.6, 1.3, ("diagonal_smear", "stretch", "apex", "fall")),
    "sleepy": (0.95, 0.9, 0.75, 0.55, ("slump", "stretch", "air", "fall")),
    "running": (0.7, 0.55, 0.5, 0.75, ("horizontal_smear", "diagonal_smear", "air", "fall")),
    "sideways": (0.5, 0.65, 0.5, 0.8, ("diagonal_smear", "air", "air", "asym_impact")),
    "tuck_roll": (0.6, 0.7, 0.8, 1.1, ("stretch", "rolling_ball", "twisted", "rolling_ball", "side_flop")),
    "vault": (0.75, 0.7, 0.6, 1.25, ("double_arch", "diagonal_smear", "air", "fall")),
    "careful_drop": (1.0, 0.85, 0.65, 0.2, ("curious_lean", "drag_tail", "fall", "vertical_noodle")),
}

MOODS = (
    "content",
    "curious",
    "playful",
    "sleepy",
    "asleep",
    "waking",
    "attentive",
    "thinking",
    "focused",
    "excited",
    "proud",
    "helpful",
    "concerned",
    "startled",
    "cautious",
    "shy",
    "bored",
    "restless",
    "mischievous",
    "overwhelmed",
    "peckish",
    "overworked",
    "recovering",
)

MOOD_ACTIONS = {
    "content": ("blink", "nod", "look_left"),
    "curious": ("edge_peek", "scratch", "look_up"),
    "playful": ("roll", "spin", "dance", "somersault", "bounce"),
    "sleepy": ("yawn", "melt", "rest"),
    "asleep": ("rest",),
    "waking": ("reform", "yawn"),
    "attentive": ("look_right", "nod"),
    "thinking": ("pace", "scratch", "look_up"),
    "focused": ("blink", "nod"),
    "excited": ("cheer", "bounce", "dance"),
    "proud": ("applaud", "cheer", "nod"),
    "helpful": ("point_left", "point_right"),
    "concerned": ("edge_peek", "look_up"),
    "startled": ("retreat", "bounce"),
    "cautious": ("tiptoe", "edge_peek"),
    "shy": ("retreat", "look_left"),
    "bored": ("melt", "pace", "reform"),
    "restless": ("pace", "scoot", "crawl"),
    "mischievous": ("tiptoe", "turn", "edge_peek", "shake_head"),
    "overwhelmed": ("rest", "yawn", "blink"),
    "peckish": ("look_left", "scoot"),
    "overworked": ("yawn", "melt", "blink"),
    "recovering": ("reform", "yawn", "nod"),
}

MOOD_CATEGORY = {
    "content": "quiet",
    "curious": "curiosity",
    "playful": "play",
    "sleepy": "sleep",
    "asleep": "sleep",
    "waking": "sleep",
    "attentive": "running",
    "thinking": "running",
    "focused": "running",
    "excited": "play",
    "proud": "success",
    "helpful": "input",
    "concerned": "concern",
    "startled": "greetings",
    "cautious": "concern",
    "shy": "quiet",
    "bored": "quiet",
    "restless": "play",
    "mischievous": "play",
    "overwhelmed": "workload",
    "peckish": "food",
    "overworked": "workload",
    "recovering": "workload",
}
